# Generated by Django 5.0.6 on 2026-05-26 10:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                (
                    "role",
                    models.CharField(
                        choices=[("seeker", "Roommate Seeker"), ("lister", "Room Lister"), ("both", "Both")],
                        default="seeker",
                        max_length=10,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                        ],
                        default="unverified",
                        max_length=12,
                    ),
                ),
                ("is_banned", models.BooleanField(default=False)),
                (
                    "ban_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("spam", "Spam"),
                            ("harassment", "Harassment"),
                            ("fraud", "Fraud"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("banned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "average_rating",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                (
                    "banned_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Preference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("min_budget", models.PositiveIntegerField(default=0, help_text="Minimum monthly budget in KES")),
                ("max_budget", models.PositiveIntegerField(default=50000, help_text="Maximum monthly budget in KES")),
                (
                    "preferred_gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female"), ("any", "Any")], default="any", max_length=10
                    ),
                ),
                ("preferred_age_min", models.PositiveIntegerField(default=18)),
                ("preferred_age_max", models.PositiveIntegerField(default=65)),
                (
                    "sleep_schedule",
                    models.CharField(
                        choices=[("early", "Early Bird"), ("night", "Night Owl"), ("flexible", "Flexible")],
                        default="flexible",
                        max_length=10,
                    ),
                ),
                (
                    "cleanliness",
                    models.CharField(
                        choices=[
                            ("very_clean", "Very Clean"),
                            ("clean", "Clean"),
                            ("moderate", "Moderate"),
                            ("messy", "Messy"),
                        ],
                        default="moderate",
                        max_length=15,
                    ),
                ),
                (
                    "noise_tolerance",
                    models.CharField(
                        choices=[("quiet", "Quiet"), ("moderate", "Moderate Noise"), ("loud", "Loud")],
                        default="moderate",
                        max_length=10,
                    ),
                ),
                ("smoking_ok", models.BooleanField(default=False)),
                ("pets_ok", models.BooleanField(default=False)),
                ("guests_ok", models.BooleanField(default=True)),
                (
                    "max_distance_km",
                    models.PositiveIntegerField(default=10, help_text="Maximum distance from preferred area in km"),
                ),
                ("preferred_areas", models.JSONField(default=list, help_text="List of preferred area IDs")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "preferences",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(default="", max_length=50)),
                ("last_name", models.CharField(default="", max_length=50)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("bio", models.TextField(blank=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(default="", max_length=100)),
                ("area", models.CharField(default="", max_length=100)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("profile_picture", models.ImageField(blank=True, upload_to="profiles/")),
                ("facebook", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("id_document", models.ImageField(blank=True, upload_to="verification/")),
                ("is_verified", models.BooleanField(default=False)),
                ("is_complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="profile", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
