# Generated by Django 5.0.6 on 2026-04-08 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[("seeker", "Room Seeker"), ("lister", "Room Lister"), ("both", "Both")],
                        default="seeker",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_banned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Preference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("min_budget", models.PositiveIntegerField(default=0)),
                ("max_budget", models.PositiveIntegerField(default=50000)),
                (
                    "gender_preference",
                    models.CharField(
                        choices=[("male", "Male only"), ("female", "Female only"), ("any", "Any gender")],
                        default="any",
                        max_length=10,
                    ),
                ),
                (
                    "sleep_schedule",
                    models.CharField(
                        choices=[
                            ("early", "Early bird (before 10pm)"),
                            ("night", "Night owl (after midnight)"),
                            ("flexible", "Flexible"),
                        ],
                        default="flexible",
                        max_length=10,
                    ),
                ),
                (
                    "cleanliness",
                    models.CharField(
                        choices=[("very_clean", "Very clean"), ("clean", "Clean"), ("relaxed", "Relaxed")],
                        default="clean",
                        max_length=10,
                    ),
                ),
                (
                    "noise_level",
                    models.CharField(
                        choices=[("quiet", "Quiet"), ("moderate", "Moderate"), ("lively", "Lively")],
                        default="moderate",
                        max_length=10,
                    ),
                ),
                ("smoking_ok", models.BooleanField(default=False)),
                ("pets_ok", models.BooleanField(default=False)),
                ("guests_ok", models.BooleanField(default=True)),
                ("preferred_city", models.CharField(blank=True, max_length=100)),
                ("preferred_area", models.CharField(blank=True, max_length=100)),
                ("max_distance_km", models.PositiveIntegerField(default=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "preferences",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=150)),
                ("bio", models.TextField(blank=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not", "Prefer not to say"),
                        ],
                        max_length=10,
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="profiles/")),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("area", models.CharField(blank=True, max_length=100)),
                ("average_rating", models.FloatField(default=0.0)),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="profile", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "profiles",
            },
        ),
    ]
