# Generated by Django 5.0.6 on 2026-04-08 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("rent", models.PositiveIntegerField(help_text="Monthly rent in KES")),
                ("rooms_available", models.PositiveIntegerField(default=1)),
                (
                    "furnished",
                    models.CharField(
                        choices=[
                            ("furnished", "Fully Furnished"),
                            ("semi", "Semi Furnished"),
                            ("unfurnished", "Unfurnished"),
                        ],
                        default="unfurnished",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("taken", "Taken"), ("paused", "Paused")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("has_wifi", models.BooleanField(default=False)),
                ("has_parking", models.BooleanField(default=False)),
                ("has_gym", models.BooleanField(default=False)),
                ("has_pool", models.BooleanField(default=False)),
                ("has_security", models.BooleanField(default=False)),
                ("water_included", models.BooleanField(default=False)),
                ("electricity_included", models.BooleanField(default=False)),
                ("preferred_gender", models.CharField(default="any", max_length=10)),
                ("smoking_allowed", models.BooleanField(default=False)),
                ("pets_allowed", models.BooleanField(default=False)),
                ("guests_allowed", models.BooleanField(default=True)),
                ("is_flagged", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "listings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ListingPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="listings/")),
                ("is_cover", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="listings.listing"
                    ),
                ),
            ],
            options={
                "db_table": "listing_photos",
            },
        ),
    ]
